export const tableBgColors: { [key: string]: string } = {
  blue: 'bg-blue-100',
  ruby: 'bg-rose-100',
  gray: 'bg-gray-100',
  gold: 'bg-yellow-100',
  bronze: 'bg-amber-100',
  brown: 'bg-stone-100',
  yellow: 'bg-yellow-100',
  amber: 'bg-amber-100',
  orange: 'bg-orange-100',
  tomato: 'bg-red-100',
  red: 'bg-red-100',
  crimson: 'bg-rose-100',
  pink: 'bg-pink-100',
  plum: 'bg-fuchsia-100',
  purple: 'bg-purple-100',
  violet: 'bg-violet-100',
  iris: 'bg-indigo-100',
  indigo: 'bg-indigo-100',
  cyan: 'bg-cyan-100',
  teal: 'bg-teal-100',
  jade: 'bg-emerald-100',
  green: 'bg-green-100',
  grass: 'bg-lime-100',
  lime: 'bg-lime-100',
  mint: 'bg-emerald-100',
  sky: 'bg-sky-100',
}

export const tableHoverBgColors: { [key: string]: string } = {
  blue: 'hover:bg-blue-200',
  ruby: 'hover:bg-rose-200',
  gray: 'hover:bg-gray-200',
  gold: 'hover:bg-yellow-200',
  bronze: 'hover:bg-amber-200',
  brown: 'hover:bg-stone-200',
  yellow: 'hover:bg-yellow-200',
  amber: 'hover:bg-amber-200',
  orange: 'hover:bg-orange-200',
  tomato: 'hover:bg-red-200',
  red: 'hover:bg-red-200',
  crimson: 'hover:bg-rose-200',
  pink: 'hover:bg-pink-200',
  plum: 'hover:bg-fuchsia-200',
  purple: 'hover:bg-purple-200',
  violet: 'hover:bg-violet-200',
  iris: 'hover:bg-indigo-200',
  indigo: 'hover:bg-indigo-200',
  cyan: 'hover:bg-cyan-200',
  teal: 'hover:bg-teal-200',
  jade: 'hover:bg-emerald-200',
  green: 'hover:bg-green-200',
  grass: 'hover:bg-lime-200',
  lime: 'hover:bg-lime-200',
  mint: 'hover:bg-emerald-200',
  sky: 'hover:bg-sky-200',
}

export const rowHoverBgColors: { [key: string]: string } = {
  blue: 'hover:bg-blue-50',
  ruby: 'hover:bg-rose-50',
  gray: 'hover:bg-gray-50',
  gold: 'hover:bg-yellow-50',
  bronze: 'hover:bg-amber-50',
  brown: 'hover:bg-stone-50',
  yellow: 'hover:bg-yellow-50',
  amber: 'hover:bg-amber-50',
  orange: 'hover:bg-orange-50',
  tomato: 'hover:bg-red-50',
  red: 'hover:bg-red-50',
  crimson: 'hover:bg-rose-50',
  pink: 'hover:bg-pink-50',
  plum: 'hover:bg-fuchsia-50',
  purple: 'hover:bg-purple-50',
  violet: 'hover:bg-violet-50',
  iris: 'hover:bg-indigo-50',
  indigo: 'hover:bg-indigo-50',
  cyan: 'hover:bg-cyan-50',
  teal: 'hover:bg-teal-50',
  jade: 'hover:bg-emerald-50',
  green: 'hover:bg-green-50',
  grass: 'hover:bg-lime-50',
  lime: 'hover:bg-lime-50',
  mint: 'hover:bg-emerald-50',
  sky: 'hover:bg-sky-50',
}

export const ringColors: { [key: string]: string } = {
  blue: 'ring-blue-100',
  ruby: 'ring-rose-100',
  gray: 'ring-gray-100',
  gold: 'ring-yellow-100',
  bronze: 'ring-amber-100',
  brown: 'ring-stone-100',
  yellow: 'ring-yellow-100',
  amber: 'ring-amber-100',
  orange: 'ring-orange-100',
  tomato: 'ring-red-100',
  red: 'ring-red-100',
  crimson: 'ring-rose-100',
  pink: 'ring-pink-100',
  plum: 'ring-fuchsia-100',
  purple: 'ring-purple-100',
  violet: 'ring-violet-100',
  iris: 'ring-indigo-100',
  indigo: 'ring-indigo-100',
  cyan: 'ring-cyan-100',
  teal: 'ring-teal-100',
  jade: 'ring-emerald-100',
  green: 'ring-green-100',
  grass: 'ring-lime-100',
  lime: 'ring-lime-100',
  mint: 'ring-emerald-100',
  sky: 'ring-sky-100',
}

export const paginationBgColors: { [key: string]: string } = {
  blue: 'bg-blue-300',
  ruby: 'bg-rose-300',
  gray: 'bg-gray-300',
  gold: 'bg-yellow-300',
  bronze: 'bg-amber-300',
  brown: 'bg-stone-300',
  yellow: 'bg-yellow-300',
  amber: 'bg-amber-300',
  orange: 'bg-orange-300',
  tomato: 'bg-red-300',
  red: 'bg-red-300',
  crimson: 'bg-rose-300',
  pink: 'bg-pink-300',
  plum: 'bg-fuchsia-300',
  purple: 'bg-purple-300',
  violet: 'bg-violet-300',
  iris: 'bg-indigo-300',
  indigo: 'bg-indigo-300',
  cyan: 'bg-cyan-300',
  teal: 'bg-teal-300',
  jade: 'bg-emerald-300',
  green: 'bg-green-300',
  grass: 'bg-lime-300',
  lime: 'bg-lime-300',
  mint: 'bg-emerald-300',
  sky: 'bg-sky-300',
}

export const paginationHoverBgColors: { [key: string]: string } = {
  blue: 'hover:bg-blue-400',
  ruby: 'hover:bg-rose-400',
  gray: 'hover:bg-gray-400',
  gold: 'hover:bg-yellow-400',
  bronze: 'hover:bg-amber-400',
  brown: 'hover:bg-stone-400',
  yellow: 'hover:bg-yellow-400',
  amber: 'hover:bg-amber-400',
  orange: 'hover:bg-orange-400',
  tomato: 'hover:bg-red-400',
  red: 'hover:bg-red-400',
  crimson: 'hover:bg-rose-400',
  pink: 'hover:bg-pink-400',
  plum: 'hover:bg-fuchsia-400',
  purple: 'hover:bg-purple-400',
  violet: 'hover:bg-violet-400',
  iris: 'hover:bg-indigo-400',
  indigo: 'hover:bg-indigo-400',
  cyan: 'hover:bg-cyan-400',
  teal: 'hover:bg-teal-400',
  jade: 'hover:bg-emerald-400',
  green: 'hover:bg-green-400',
  grass: 'hover:bg-lime-400',
  lime: 'hover:bg-lime-400',
  mint: 'hover:bg-emerald-400',
  sky: 'hover:bg-sky-400',
}