export const api = {
  searchCountries: {
    url: "/collection/search",
    description: "Search countries by name or code",
    methods: "GET" as const,
    response: "countryRes",
    query: "countrySearchQuery",
    withOptions: false,
  },
  countries: {
    url: "/collection/get-all",
    description: "Get all countries",
    methods: "POST" as const,
    response: "countryRes",
    body: "countryBody",
    withOptions: false,
  },
  countriesPaged: {
    url: "/collection/page",
    description: "Get a page of countries (server-side pagination + search)",
    methods: "POST" as const,
    response: "countryPagedRes",
    body: "countryPageBody",
    withOptions: false,
  },
  countriesPagedGet: {
    url: "/collection/page",
    description: "Get a page of countries via the query string (the data table's query placement)",
    methods: "GET" as const,
    response: "countryPagedRes",
    query: "countryPageQuery",
    withOptions: false,
  },
  // One region's countries: the Server filter & sort demo maps a filter into
  // the `:region` URL param.
  regionCountriesPaged: {
    url: "/collection/region/:region/page",
    description: "Get a page of one region's countries (`:region` = region id or \"all\")",
    methods: "GET" as const,
    response: "countryPagedRes",
    query: "countryPageQuery",
    parameter: "regionPageParams",
    withOptions: false,
  },
  countryDetail: {
    url: "/collection/detail/:id",
    description: "Get a single country by id (state-loader demo)",
    methods: "GET" as const,
    response: "countryDetailRes",
    parameter: "countryParam",
    withOptions: false,
  },
  createCountry: {
    url: "/collection/create/691e9963992636eb1560eadb",
    description: "Create country",
    methods: "POST" as const,
    response: "countryRes",
    body: "countryBody",
    withOptions: false,
  },
  updateCountry: {
    url: "/collection/update/691e9963992636eb1560eadb/:id",
    description: "Update country",
    methods: "PATCH" as const,
    response: "countryRes",
    body: "countryBody",
    parameter: "countryParam",
    withOptions: false,
  },
  deleteCountry: {
    url: "/collection/delete/691e9963992636eb1560eadb/:id",
    description: "Delete country",
    methods: "DELETE" as const,
    response: "countryRes",
    parameter: "countryParam",
    withOptions: false,
  },
  // Languages of a country — the FormList demo's CRUD (`:country` = id or code).
  countryLanguages: {
    url: "/collection/languages/:country",
    description: "Languages of a country",
    methods: "GET" as const,
    response: "languageRes",
    parameter: "languageCountryParam",
    withOptions: false,
  },
  createLanguage: {
    url: "/collection/languages/:country",
    description: "Add a language to a country",
    methods: "POST" as const,
    response: "languageRes",
    parameter: "languageCountryParam",
    body: "languageBody",
    withOptions: false,
  },
  updateLanguage: {
    url: "/collection/languages/:country/:id",
    description: "Update a language",
    methods: "PATCH" as const,
    response: "languageRes",
    parameter: "languageParam",
    body: "languageBody",
    withOptions: false,
  },
  deleteLanguage: {
    url: "/collection/languages/:country/:id",
    description: "Delete a language",
    methods: "DELETE" as const,
    response: "languageRes",
    parameter: "languageParam",
    withOptions: false,
  },
  // Form list demo page — contacts (full CRUD) and notes (create + delete).
  contacts: {
    url: "/collection/contacts",
    description: "List contacts",
    methods: "GET" as const,
    response: "contactRes",
    withOptions: false,
  },
  createContact: {
    url: "/collection/contacts",
    description: "Create a contact",
    methods: "POST" as const,
    response: "contactRes",
    body: "contactBody",
    withOptions: false,
  },
  updateContact: {
    url: "/collection/contacts/:id",
    description: "Update a contact",
    methods: "PATCH" as const,
    response: "contactRes",
    parameter: "idParam",
    body: "contactBody",
    withOptions: false,
  },
  deleteContact: {
    url: "/collection/contacts/:id",
    description: "Delete a contact",
    methods: "DELETE" as const,
    response: "contactRes",
    parameter: "idParam",
    withOptions: false,
  },
  notes: {
    url: "/collection/notes",
    description: "List notes",
    methods: "GET" as const,
    response: "noteRes",
    withOptions: false,
  },
  createNote: {
    url: "/collection/notes",
    description: "Create a note",
    methods: "POST" as const,
    response: "noteRes",
    body: "noteBody",
    withOptions: false,
  },
  deleteNote: {
    url: "/collection/notes/:id",
    description: "Delete a note",
    methods: "DELETE" as const,
    response: "noteRes",
    parameter: "idParam",
    withOptions: false,
  },
  // Regions, each with its `countries[]` — the Repeater demo's nested source.
  regions: {
    url: "/collection/regions",
    description: "List regions with their countries",
    methods: "GET" as const,
    response: "regionRes",
    withOptions: false,
  },
  // Flat country rows with their region (Table layout demo).
  regionCountries: {
    url: "/collection/region-countries",
    description: "List countries with their region, one row each",
    methods: "GET" as const,
    response: "regionCountryRes",
    withOptions: false,
  },
};
