import type { Bin, Container } from "@gummy-ui/ui";
import { DEFAULT_CONTAINER_GRID } from "@gummy-ui/ui";

/** Country form bins — demos container grid + per-item justifySelf / alignSelf */
export const countryDetail: Bin[] = [
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "hidden",
    element: {
      name: "_id",
      dataType: "string",
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    justifySelf: "start",
    alignSelf: "end",
    element: {
      text: "Country details",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "textfield",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "code",
      label: "Code",
      dataType: "string",
      isRequired: true,
      errorMessage: "code is required",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "textfield",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "name",
      label: "Name",
      dataType: "string",
      isRequired: true,
      errorMessage: "name is required",
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "autocomplete",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "relatedCountryId",
      label: "Related Country",
      dataType: "string",
      isRequired: false,
      errorMessage: "Related country is required",
      canObserve: false,
      observeTo: "",
      isSingleLoad: false,
      inputIcon: "globe",
      keys: {
        id: "_id",
        search: "name",
        display: "name",
      },
      defaultData: {},
      options: [],
      api: {
        name: "searchCountries",
        paths: ["data"],
        query: {
          search: { type: "value", key: "search" },
        },
      },
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "multiAutocomplete",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "relatedCountryIds",
      label: "Related Countries",
      dataType: "array",
      isRequired: false,
      errorMessage: "Related countries are required",
      canObserve: false,
      observeTo: "",
      isSingleLoad: false,
      inputIcon: "flag",
      keys: {
        id: "_id",
        search: "name",
        display: "name",
      },
      defaultData: {},
      options: [],
      api: {
        name: "searchCountries",
        paths: ["data"],
        query: {
          search: { type: "value", key: "search" },
        },
      },
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "daterangepicker",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "activePeriod",
      label: "Active Period",
      dataType: "daterange",
      placeholder: "Select date range",
      displayFormat: "dd/MM/yyyy",
      isFullWidth: true,
      clearable: true,
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    justifySelf: "center",
    alignSelf: "center",
    element: {
      text: "Actions",
    },
  },
  {
    sm: "12",
    md: "8",
    lg: "9",
    xl: "9",
    type: "empty",
    justifySelf: "stretch",
    alignSelf: "center",
  },
  {
    sm: "12",
    md: "4",
    lg: "3",
    xl: "3",
    type: "button",
    align: "end",
    justifySelf: "end",
    alignSelf: "center",
    condition: {
      right: { key: "dtCountry", path: "_id" },
      operator: "neq",
      left: { val: undefined },
    },
    element: {
      label: "Update",
      modalId: "modalGroup",
      confirmBox: {
        title: "Update Country",
        description: "Are you sure you want to update this country?",
        True: ["StartLoading", "SubmitFormToPatchAPI", "StopLoading", "CloseModal"],
        False: [],
      },
      reloadDataTable: "dtCountry",
      actions: ["ConfirmBox"],
      api: {
        name: "updateCountry",
      },
      snackbarSuccess: { type: "success", message: "Country updated successfully" },
      snackbarError: "$exception",
    },
  },
  {
    sm: "12",
    md: "4",
    lg: "3",
    xl: "3",
    type: "button",
    align: "end",
    justifySelf: "end",
    alignSelf: "center",
    condition: {
      right: { key: "dtCountry", path: "_id" },
      operator: "eq",
      left: { val: undefined },
    },
    element: {
      label: "Create",
      modalId: "modalGroup",
      confirmBox: {
        title: "Create Country",
        description: "Are you sure you want to create this country?",
        True: ["StartLoading", "SubmitFormToPostAPI", "StopLoading", "CloseModal"],
        False: [],
      },
      reloadDataTable: "dtCountry",
      actions: ["ConfirmBox"],
      api: {
        name: "createCountry",
      },
      snackbarSuccess: { type: "success", message: "Country created successfully" },
      snackbarError: "$exception",
    },
  },
];

export const containerCountryDetail: Container = {
  id: "7afc5dc0-d446-4ff4-ab17-8d81127e5ab2",
  name: "GroupList",
  contextData: "dtCountry",
  isArray: false,
  bins: countryDetail,
  ...DEFAULT_CONTAINER_GRID,
  gap: "4",
  justifyItems: "stretch",
  alignItems: "center",
  justifyContent: "start",
  alignContent: "start",
  gridAutoFlow: "row",
};

export const groupList: Bin[] = [
  {
    type: "empty",
    sm: "11",
    md: "11",
    lg: "11",
    xl: "11",
    justifySelf: "stretch",
    alignSelf: "center",
  },
  {
    type: "modal",
    sm: "1",
    md: "1",
    lg: "1",
    xl: "1",
    align: "end",
    justifySelf: "end",
    alignSelf: "center",
    element: {
      id: "modalGroup",
      title: "Create Country",
      description: "modal",
      container: containerCountryDetail,
      maxWidth: "800px",
      minWidth: "700px",
      trigger: {
        label: "",
        actions: ["ClearCurrentFormSelected"],
        icon: "puls",
      },
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "datatable",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "dtCountry",
      title: "Countries",
      modalContainer: containerCountryDetail,
      modalMaxWidth: "800px",
      modalMinWidth: "700px",
      canEdit: true,
      canDelete: true,
      columns: [
        {
          accessor: "code",
          header: "Code",
          enableColumnFilter: true,
          enableSorting: true,
          align: "start",
        },
        {
          accessor: "name",
          header: "Name",
          enableColumnFilter: true,
          enableSorting: true,
          align: "start",
        },
        {
          accessor: "updated_at",
          header: "Update Date",
          enableColumnFilter: true,
          enableSorting: true,
          align: "start",
          useDateFormat: "DD/MM/YYYY HH:mm:ss",
        },
        {
          accessor: "updated_by_name",
          header: "Updated By",
          enableColumnFilter: true,
          enableSorting: true,
          align: "start",
        },
      ],
      apiDeleteInfo: {
        name: "deleteCountry",
        params: { id: "_id" },
        confirmBox: {
          title: "Delete Country",
          description: "Are you sure you want to delete this country?",
          True: ["StartLoading", "SubmitFormToDeleteAPI", "StopLoading"],
          False: [],
        },
        isReload: true,
        snackbarSuccess: { type: "success", message: "Country deleted successfully" },
        snackbarError: "$exception",
      },
      api: {
        name: "countries",
        paths: ["data"],
        body: {
          collectionId: { type: "value", key: "collectionId", value: "691e9963992636eb1560eadb" },
          offset: { type: "value", key: "offset", value: 0 },
          limit: { type: "value", key: "limit", value: 100 },
        },
      },
    },
  },
];

export const containerCountryList: Container[] = [
  {
    id: "7afc5dc0-d446-4ff4-ab17-8d81127e5ab2",
    name: "GroupList",
    isArray: false,
    bins: groupList,
    ...DEFAULT_CONTAINER_GRID,
    gap: "3",
    justifyItems: "stretch",
    alignItems: "start",
    justifyContent: "space-between",
    alignContent: "start",
  },
];
