import type { Bin, Container } from "@gummy-ui/ui";
import { DEFAULT_CONTAINER_GRID } from "@gummy-ui/ui";

/** Country form bins — demos container grid + per-item justifySelf / alignSelf */
export const countryDetail: Bin[] = [
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "hidden",
    element: {
      name: "_id",
      dataType: "string",
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    justifySelf: "start",
    alignSelf: "end",
    element: {
      text: "Country details",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "3",
    lg: "3",
    xl: "3",
    type: "avatar",
    justifySelf: "center",
    alignSelf: "center",
    element: {
      src: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=150&h=150&fit=crop&crop=face",
      alt: "Country Representative",
      size: "lg",
      fallback: "CR",
    },
  },
  {
    sm: "12",
    md: "3",
    lg: "3",
    xl: "3",
    type: "avatar",
    justifySelf: "center",
    alignSelf: "center",
    element: {
      src: "invalid-url",
      alt: "Fallback Example",
      size: "md",
      fallback: "FB",
    },
  },
  {
    sm: "12",
    md: "3",
    lg: "3",
    xl: "3",
    type: "avatar",
    justifySelf: "center",
    alignSelf: "center",
    element: {
      alt: "No Image",
      size: "sm",
    },
  },
  {
    sm: "12",
    md: "3",
    lg: "3",
    xl: "3",
    type: "avatar",
    justifySelf: "center",
    alignSelf: "center",
    element: {
      size: "xs",
      className: "border-2 border-blue-500",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "textfield",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "code",
      label: "Code",
      dataType: "string",
      isRequired: true,
      errorMessage: "code is required",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "textfield",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "name",
      label: "Name",
      dataType: "string",
      isRequired: true,
      errorMessage: "name is required",
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "autocomplete",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "relatedCountryId",
      label: "Related Country",
      subtitle: "Choose a country that has diplomatic relations",
      dataType: "string",
      isRequired: false,
      errorMessage: "Related country is required",
      canObserve: false,
      observeTo: "",
      isSingleLoad: false,
      inputIcon: "globe",
      itemIcon: "mapPin",
      itemSubtitle: "name",
      itemAvatar: "avatar",
      keys: {
        id: "_id",
        search: "name",
        display: "name",
      },
      defaultData: {},
      options: [
        {
          _id: "1",
          name: "United States",
          code: "US",
          avatar: "https://flagcdn.com/w40/us.png",
        },
        {
          _id: "2",
          name: "United Kingdom",
          code: "GB",
          avatar: {
            src: "https://flagcdn.com/w40/gb.png",
            alt: "UK Flag",
            fallback: "UK"
          },
        },
        {
          _id: "3",
          name: "Germany",
          code: "DE",
          avatar: {
            src: "https://flagcdn.com/w40/de.png",
            alt: "German Flag"
          },
        },
        {
          _id: "4",
          name: "France",
          code: "FR",
          avatar: "https://flagcdn.com/w40/fr.png",
        },
        {
          _id: "5",
          name: "Japan",
          code: "JP",
          avatar: {
            src: "https://flagcdn.com/w40/jp.png",
            fallback: "JP"
          },
        }
      ],
      api: {
        name: "searchCountries",
        paths: ["data"],
        query: {
          search: { type: "value", key: "search" },
        },
      },
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "multiAutocomplete",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "relatedCountryIds",
      label: "Related Countries",
      dataType: "array",
      isRequired: false,
      errorMessage: "Related countries are required",
      canObserve: false,
      observeTo: "",
      isSingleLoad: false,
      inputIcon: "flag",
      keys: {
        id: "_id",
        search: "name",
        display: "name",
      },
      defaultData: {},
      options: [],
      api: {
        name: "searchCountries",
        paths: ["data"],
        query: {
          search: { type: "value", key: "search" },
        },
      },
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "autocomplete",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "regionId",
      label: "Region",
      dataType: "string",
      isRequired: false,
      errorMessage: "Region is required",
      canObserve: false,
      observeTo: "",
      isSingleLoad: false,
      inputIcon: "map",
      itemAvatar: "avatar",
      keys: {
        id: "_id",
        search: "name",
        display: "name",
      },
      defaultData: {},
      options: [],
      api: {
        name: "searchCountries",
        paths: ["data"],
        query: {
          search: { type: "value", key: "search" },
        },
      },
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "autocomplete",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "capitalCityId",
      label: "Capital City",
      subtitle: "Select the administrative capital city",
      dataType: "string",
      isRequired: false,
      errorMessage: "Capital city is required",
      canObserve: false,
      observeTo: "",
      isSingleLoad: false,
      inputIcon: "home",
      itemIcon: "mapPin",
      itemSubtitle: "code",
      keys: {
        id: "_id",
        search: "name",
        display: "name",
      },
      defaultData: {},
      options: [],
      api: {
        name: "searchCountries",
        paths: ["data"],
        query: {
          search: { type: "value", key: "search" },
        },
      },
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "autocomplete",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "currencyId",
      label: "Currency",
      dataType: "string",
      isRequired: false,
      errorMessage: "Currency is required",
      canObserve: false,
      observeTo: "",
      isSingleLoad: false,
      inputIcon: "dollarSign",
      itemAvatar: "avatar",
      keys: {
        id: "_id",
        search: "name",
        display: "name",
      },
      defaultData: {},
      options: [],
      api: {
        name: "searchCountries",
        paths: ["data"],
        query: {
          search: { type: "value", key: "search" },
        },
      },
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "autocomplete",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "languageId",
      label: "Primary Language",
      subtitle: "The most widely spoken official language",
      dataType: "string",
      isRequired: false,
      errorMessage: "Language is required",
      canObserve: false,
      observeTo: "",
      isSingleLoad: false,
      inputIcon: "globe",
      itemIcon: "hash",
      keys: {
        id: "_id",
        search: "name",
        display: "name",
      },
      defaultData: {},
      options: [],
      api: {
        name: "searchCountries",
        paths: ["data"],
        query: {
          search: { type: "value", key: "search" },
        },
      },
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "autocomplete",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "timezoneId",
      label: "Timezone",
      dataType: "string",
      isRequired: false,
      errorMessage: "Timezone is required",
      canObserve: false,
      observeTo: "",
      isSingleLoad: false,
      inputIcon: "clock",
      keys: {
        id: "_id",
        search: "name",
        display: "name",
      },
      defaultData: {},
      options: [],
      api: {
        name: "searchCountries",
        paths: ["data"],
        query: {
          search: { type: "value", key: "search" },
        },
      },
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "autocomplete",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "continentId",
      label: "Continent",
      dataType: "string",
      isRequired: false,
      errorMessage: "Continent is required",
      canObserve: false,
      observeTo: "",
      isSingleLoad: false,
      inputIcon: "compass",
      itemIcon: "globe", 
      itemSubtitle: "name",
      keys: {
        id: "_id",
        search: "name",
        display: "name",
      },
      defaultData: {},
      options: [],
      api: {
        name: "searchCountries",
        paths: ["data"],
        query: {
          search: { type: "value", key: "search" },
        },
      },
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "autocomplete",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "governmentTypeId",
      label: "Government Type",
      dataType: "string",
      isRequired: false,
      errorMessage: "Government type is required",
      canObserve: false,
      observeTo: "",
      isSingleLoad: false,
      inputIcon: "award",
      keys: {
        id: "_id",
        search: "name",
        display: "name",
      },
      defaultData: {},
      options: [],
      api: {
        name: "searchCountries",
        paths: ["data"],
        query: {
          search: { type: "value", key: "search" },
        },
      },
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "autocomplete",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "phoneCodeId",
      label: "Phone Code",
      dataType: "string",
      isRequired: false,
      errorMessage: "Phone code is required",
      canObserve: false,
      observeTo: "",
      isSingleLoad: false,
      inputIcon: "phone",
      itemIcon: "hash",
      keys: {
        id: "_id",
        search: "name",
        display: "name",
      },
      defaultData: {},
      options: [],
      api: {
        name: "searchCountries",
        paths: ["data"],
        query: {
          search: { type: "value", key: "search" },
        },
      },
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "daterangepicker",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "activePeriod",
      label: "Active Period",
      dataType: "daterange",
      placeholder: "Select date range",
      displayFormat: "dd/MM/yyyy",
      isFullWidth: true,
      clearable: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "daterangepicker",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "validityPeriod",
      label: "Validity Period",
      placeholder: "Select validity period",
      dataType: "daterange",
      isRequired: true,
      errorMessage: "Validity period is required",
      helperText: "Select the period when this data is valid",
      displayFormat: "yyyy-MM-dd",
      clearable: false,
      size: "2",
      radius: "medium",
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      text: "Attachments",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "uploadimage",
    justifySelf: "stretch",
    alignSelf: "start",
    element: {
      name: "flagImage",
      label: "Flag Image (API Upload)",
      dataType: "string",
      valueFormat: "api",
      uploadApi: {
        uploadUrl: "/upload/single",
        deleteUrl: "/upload/:filename",
        fieldName: "image",
        responsePath: "data.url",
      },
      isRequired: false,
      helperText: "Upload the country flag via API (PNG/JPG, max 2 MB)",
      accept: "image/png,image/jpeg",
      maxSizeMB: 2,
      previewHeight: 160,
      isFullWidth: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "uploadfile",
    justifySelf: "stretch",
    alignSelf: "start",
    element: {
      name: "documents",
      label: "Supporting Documents (API Upload)",
      dataType: "array",
      valueFormat: "api",
      uploadApi: {
        uploadUrl: "/upload/single",
        deleteUrl: "/upload/:filename",
        fieldName: "image",
        responsePath: "data.url",
      },
      isRequired: false,
      helperText: "Attach related documents via API (max 3 files, 5 MB each)",
      accept: ".pdf,.doc,.docx,.xlsx,.csv,image/*",
      multiple: true,
      maxFiles: 3,
      maxSizeMB: 5,
      isFullWidth: true,
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    justifySelf: "center",
    alignSelf: "center",
    element: {
      text: "Actions",
    },
  },
  {
    sm: "12",
    md: "8",
    lg: "9",
    xl: "9",
    type: "empty",
    justifySelf: "stretch",
    alignSelf: "center",
  },
  {
    sm: "12",
    md: "4",
    lg: "3",
    xl: "3",
    type: "button",
    align: "end",
    justifySelf: "end",
    alignSelf: "center",
    condition: {
      right: { key: "dtCountry", path: "_id" },
      operator: "neq",
      left: { val: undefined },
    },
    element: {
      label: "Update",
      modalId: "modalGroup",
      confirmBox: {
        title: "Update Country",
        description: "Are you sure you want to update this country?",
        True: ["StartLoading", "SubmitFormToPatchAPI", "StopLoading", "CloseModal"],
        False: [],
      },
      reloadDataTable: "dtCountry",
      actions: ["ConfirmBox"],
      api: {
        name: "updateCountry",
      },
      snackbarSuccess: { type: "success", message: "Country updated successfully" },
      snackbarError: "$exception",
    },
  },
  {
    sm: "12",
    md: "4",
    lg: "3",
    xl: "3",
    type: "button",
    align: "end",
    justifySelf: "end",
    alignSelf: "center",
    condition: {
      right: { key: "dtCountry", path: "_id" },
      operator: "eq",
      left: { val: undefined },
    },
    element: {
      label: "Create",
      modalId: "modalGroup",
      confirmBox: {
        title: "Create Country",
        description: "Are you sure you want to create this country?",
        True: ["StartLoading", "SubmitFormToPostAPI", "StopLoading", "CloseModal"],
        False: [],
      },
      reloadDataTable: "dtCountry",
      actions: ["ConfirmBox"],
      api: {
        name: "createCountry",
      },
      snackbarSuccess: { type: "success", message: "Country created successfully" },
      snackbarError: "$exception",
    },
  },
];

export const containerCountryDetail: Container = {
  id: "7afc5dc0-d446-4ff4-ab17-8d81127e5ab2",
  name: "GroupList",
  contextData: "dtCountry",
  isArray: false,
  bins: countryDetail,
  ...DEFAULT_CONTAINER_GRID,
  gap: "4",
  justifyItems: "stretch",
  alignItems: "center",
  justifyContent: "start",
  alignContent: "start",
  gridAutoFlow: "row",
};

const countryOverviewBins: Bin[] = [
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    element: {
      text: "Radio Examples",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "divider",
    justifySelf: "stretch",
    element: {
      variant: "fullWidth",
      spacing: "4px",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "radio",
    element: {
      name: "radioPlan",
      label: "Plan (static options)",
      dataType: "string",
      isRequired: false,
      orientation: "vertical",
      defaultValue: "free",
      options: [
        { value: "free", label: "Free" },
        { value: "pro", label: "Pro", helperText: "Best for individuals" },
        { value: "enterprise", label: "Enterprise", disabled: true },
      ],
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "radio",
    element: {
      name: "radioCountry",
      label: "Country (options from API)",
      dataType: "string",
      isRequired: false,
      orientation: "vertical",
      keys: { value: "code", label: "name" },
      api: {
        name: "countries",
        paths: ["data"],
      },
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    element: {
      text: "Date Picker Examples",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "divider",
    justifySelf: "stretch",
    element: {
      variant: "fullWidth",
      spacing: "4px",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "datepicker",
    element: {
      name: "basicDate",
      label: "Basic Date Picker",
      dataType: "date",
      placeholder: "Select a date",
      helperText: "Simple date selection",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "datepicker",
    element: {
      name: "dateWithMin",
      label: "Date with Min Date (Today)",
      dataType: "date",
      placeholder: "Select future date",
      minDate: new Date().toISOString().split('T')[0],
      helperText: "Cannot select past dates",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "datepicker",
    element: {
      name: "dateWithMax",
      label: "Date with Max Date (Today)",
      dataType: "date",
      placeholder: "Select past date",
      maxDate: new Date().toISOString().split('T')[0],
      helperText: "Cannot select future dates",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "datepicker",
    element: {
      name: "dateWithRange",
      label: "Date with Min & Max Range",
      dataType: "date",
      placeholder: "Select date in range",
      minDate: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      maxDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      helperText: "Select date within ±7 days",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "datepicker",
    element: {
      name: "requiredDate",
      label: "Required Date with Range",
      dataType: "date",
      isRequired: true,
      errorMessage: "Date is required",
      minDate: "2024-01-01",
      maxDate: "2024-12-31",
      helperText: "Select date in 2024",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "datepicker",
    element: {
      name: "customFormat",
      label: "Custom Display Format",
      dataType: "date",
      displayFormat: "DD/MM/YYYY",
      minDate: "2024-01-01",
      maxDate: "2025-12-31",
      helperText: "DD/MM/YYYY format",
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    element: {
      text: "DateTime Picker Examples",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "datetimepicker",
    element: {
      name: "basicDateTime",
      label: "Basic DateTime Picker",
      dataType: "datetime",
      placeholder: "Select date and time",
      helperText: "Date with time selection",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "datetimepicker",
    element: {
      name: "dateTimeWithMin",
      label: "DateTime with Min (Now)",
      dataType: "datetime",
      minDateTime: new Date().toISOString(),
      placeholder: "Select future time",
      helperText: "Cannot select past times",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "datetimepicker",
    element: {
      name: "dateTimeWithMax",
      label: "DateTime with Max (Now)",
      dataType: "datetime",
      maxDateTime: new Date().toISOString(),
      placeholder: "Select past time",
      helperText: "Cannot select future times",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "datetimepicker",
    element: {
      name: "dateTimeWithRange",
      label: "DateTime with Range",
      dataType: "datetime",
      minDateTime: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
      maxDateTime: new Date(Date.now() + 24 * 60 * 60 * 1000).toISOString(),
      helperText: "Select time within ±24 hours",
      minuteStep: 15,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "datetimepicker",
    element: {
      name: "dateTimeCustomFormat",
      label: "Custom DateTime Format",
      dataType: "datetime",
      displayFormat: "DD/MM/YYYY HH:mm",
      minDateTime: "2024-01-01T00:00:00",
      maxDateTime: "2025-12-31T23:59:59",
      helperText: "DD/MM/YYYY HH:mm format",
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    element: {
      text: "Date Range Picker Examples",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "daterangepicker",
    element: {
      name: "basicDateRange",
      label: "Basic Date Range",
      dataType: "daterange",
      placeholder: "Select date range",
      helperText: "Select start and end dates",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "daterangepicker",
    element: {
      name: "rangeWithMin",
      label: "Date Range with Min Date",
      dataType: "daterange",
      minDate: new Date().toISOString().split('T')[0],
      placeholder: "Select future range",
      helperText: "Cannot select past dates",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "daterangepicker",
    element: {
      name: "rangeWithMax",
      label: "Date Range with Max Date",
      dataType: "daterange",
      maxDate: new Date().toISOString().split('T')[0],
      placeholder: "Select past range",
      helperText: "Cannot select future dates",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "daterangepicker",
    element: {
      name: "rangeWithLimits",
      label: "Date Range with Both Limits",
      dataType: "daterange",
      minDate: "2024-01-01",
      maxDate: "2024-12-31",
      placeholder: "Select 2024 range",
      helperText: "Select dates within 2024",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "daterangepicker",
    element: {
      name: "requiredDateRange",
      label: "Required Date Range",
      dataType: "daterange",
      isRequired: true,
      errorMessage: "Date range is required",
      minDate: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      maxDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
      helperText: "Select range within ±30 days",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "daterangepicker",
    element: {
      name: "customFormatRange",
      label: "Custom Format Range",
      dataType: "daterange",
      displayFormat: "dd/MM/yyyy",
      minDate: "2023-01-01",
      maxDate: "2025-12-31",
      clearable: false,
      helperText: "dd/MM/yyyy format, not clearable",
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    element: {
      text: "Textarea Examples",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "textarea",
    element: {
      name: "basicTextarea",
      label: "Basic Textarea",
      dataType: "string",
      placeholder: "Enter your text here...",
      helperText: "Basic textarea without character limit",
      rows: 4,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "textarea",
    element: {
      name: "maxLengthTextarea",
      label: "Textarea with Max Length",
      dataType: "string",
      placeholder: "Write up to 100 characters...",
      helperText: "Character counter shows remaining/total characters",
      maxLength: 100,
      showCharCount: true,
      rows: 4,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "textarea",
    element: {
      name: "autoResizeTextarea",
      label: "Auto-Resize Textarea",
      dataType: "string",
      placeholder: "This textarea grows as you type...",
      helperText: "Auto-expands based on content length",
      autoResize: true,
      maxLength: 250,
      showCharCount: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "textarea",
    element: {
      name: "requiredTextarea",
      label: "Required Textarea with Limit",
      dataType: "string",
      placeholder: "Required field with character limit...",
      isRequired: true,
      errorMessage: "This field is required",
      maxLength: 200,
      showCharCount: true,
      rows: 3,
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    element: {
      text: "Upload Examples (Bytes Mode)",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "uploadimage",
    alignSelf: "start",
    element: {
      name: "profileImage",
      label: "Profile Image (circle)",
      dataType: "array",
      valueFormat: "bytes",
      shape: "circle",
      previewHeight: 140,
      maxSizeMB: 2,
      helperText: "Circle preview, max 2 MB, sent as byte array",
      isFullWidth: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "uploadimage",
    alignSelf: "start",
    element: {
      name: "coverImage",
      label: "Cover Image (required)",
      dataType: "array",
      valueFormat: "bytes",
      isRequired: true,
      errorMessage: "Cover image is required",
      previewHeight: 140,
      isFullWidth: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "uploadfile",
    alignSelf: "start",
    element: {
      name: "attachments",
      label: "Attachments (multiple)",
      dataType: "array",
      valueFormat: "bytes",
      multiple: true,
      maxFiles: 5,
      maxSizeMB: 10,
      helperText: "Up to 5 files, 10 MB each, sent as byte arrays",
      isFullWidth: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "uploadfile",
    alignSelf: "start",
    element: {
      name: "report",
      label: "Single PDF Report",
      dataType: "array",
      valueFormat: "bytes",
      accept: ".pdf",
      maxSizeMB: 5,
      helperText: "PDF only, max 5 MB, sent as byte array",
      isFullWidth: true,
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    element: {
      text: "Upload Examples (API Mode)",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "uploadimage",
    alignSelf: "start",
    element: {
      name: "apiImage",
      label: "Image via API",
      dataType: "string",
      valueFormat: "api",
      uploadApi: {
        uploadUrl: "/upload/single",
        deleteUrl: "/upload/:filename",
        fieldName: "image",
        responsePath: "data.url",
      },
      previewHeight: 140,
      maxSizeMB: 2,
      helperText: "Uploads to server, stores URL",
      isFullWidth: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "uploadimage",
    alignSelf: "start",
    element: {
      name: "apiCircleImage",
      label: "Circle Image via API",
      dataType: "string",
      valueFormat: "api",
      uploadApi: {
        uploadUrl: "/upload/single",
        deleteUrl: "/upload/:filename",
        fieldName: "image",
        responsePath: "data.url",
      },
      shape: "circle",
      previewHeight: 140,
      maxSizeMB: 2,
      helperText: "Circle preview with API upload",
      isFullWidth: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "uploadfile",
    alignSelf: "start",
    element: {
      name: "apiFiles",
      label: "Files via API (multiple)",
      dataType: "array",
      valueFormat: "api",
      uploadApi: {
        uploadUrl: "/upload/single",
        deleteUrl: "/upload/:filename",
        fieldName: "image",
        responsePath: "data.url",
      },
      multiple: true,
      maxFiles: 3,
      maxSizeMB: 5,
      helperText: "Up to 3 files via API, stores URLs",
      isFullWidth: true,
    },
  },
];

const countryMetadataBins: Bin[] = [
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    element: {
      text: "Country metadata",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "textfield",
    element: {
      name: "metadataSource",
      label: "Source",
      dataType: "string",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "textfield",
    element: {
      name: "metadataVersion",
      label: "Version",
      dataType: "string",
    },
  },
];

const countryTypographyBins: Bin[] = [
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "typography",
    element: {
      text: "Typography System",
      variant: "display1",
      align: "center",
      className: "mb-8",
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    element: {
      text: "Display Styles",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "typography",
    element: {
      text: "Display 1 - Hero Headlines",
      variant: "display1",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "typography",
    element: {
      text: "Display 2 - Section Headers",
      variant: "display2",
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    element: {
      text: "Headings",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "typography",
    element: {
      text: "Heading 1 - Page Title",
      variant: "h1",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "typography",
    element: {
      text: "Heading 2 - Section Title",
      variant: "h2",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "typography",
    element: {
      text: "Heading 3 - Subsection",
      variant: "h3",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "typography",
    element: {
      text: "Heading 4 - Content Group",
      variant: "h4",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "typography",
    element: {
      text: "Heading 5 - Article Title",
      variant: "h5",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "typography",
    element: {
      text: "Heading 6 - Minor Heading",
      variant: "h6",
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    element: {
      text: "Body Text & Subtitles",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "typography",
    element: {
      text: "Subtitle 1 - Section descriptions and important information that needs emphasis.",
      variant: "subtitle1",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "typography",
    element: {
      text: "Subtitle 2 - Secondary information and medium-emphasis content for supporting details.",
      variant: "subtitle2",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "typography",
    element: {
      text: "Body 1 - This is the primary body text used for main content, articles, and lengthy descriptions. It provides comfortable reading experience with optimal line height.",
      variant: "body1",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "typography",
    element: {
      text: "Body 2 - Secondary body text for less prominent content, captions under images, or supplementary information that doesn't need as much visual weight.",
      variant: "body2",
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    element: {
      text: "Specialized Text",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "4",
    lg: "4",
    xl: "4",
    type: "typography",
    element: {
      text: "Caption text for images",
      variant: "caption",
    },
  },
  {
    sm: "12",
    md: "4",
    lg: "4",
    xl: "4",
    type: "typography",
    element: {
      text: "OVERLINE TEXT",
      variant: "overline",
    },
  },
  {
    sm: "12",
    md: "4",
    lg: "4",
    xl: "4",
    type: "typography",
    element: {
      text: "Button Text",
      variant: "button",
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    element: {
      text: "Text Styling Options",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "Left aligned text",
      variant: "body1",
      align: "left",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "Center aligned text",
      variant: "body1",
      align: "center",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "Right aligned text",
      variant: "body1",
      align: "right",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "Justified text with longer content to demonstrate justify alignment behavior",
      variant: "body1",
      align: "justify",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "capitalize text",
      variant: "body1",
      transform: "capitalize",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "UPPERCASE TEXT",
      variant: "body1",
      transform: "uppercase",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "underlined text",
      variant: "body1",
      decoration: "underline",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "This is a very long text that will be truncated to show the truncate functionality",
      variant: "body1",
      truncate: true,
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    element: {
      text: "Color Variations",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "Primary color text",
      variant: "body1",
      color: "blue",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "Success color text",
      variant: "body1",
      color: "green",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "Warning color text",
      variant: "body1",
      color: "orange",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "Error color text",
      variant: "body1",
      color: "red",
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    element: {
      text: "Link Examples",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "Basic link",
      variant: "body1",
      href: "https://example.com",
      color: "blue",
      decoration: "underline",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "External link (new tab)",
      variant: "body1",
      href: "https://github.com",
      target: "_blank",
      color: "blue",
      decoration: "underline",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "Button-style link",
      variant: "button",
      href: "https://docs.example.com",
      target: "_blank",
      color: "violet",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "Heading as link",
      variant: "h3",
      href: "https://heading-link.com",
      color: "blue",
    },
  },
  // Tooltip examples
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "typography",
    element: {
      text: "Tooltip Examples",
      variant: "h2",
      className: "mt-8 mb-4",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "Hover me (top)",
      variant: "body1",
      tooltip: "This is a tooltip on the top!",
      tooltipSide: "top",
      className: "cursor-help underline decoration-dotted",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "Hover me (right)",
      variant: "body1",
      tooltip: "This tooltip appears on the right side",
      tooltipSide: "right",
      className: "cursor-help underline decoration-dotted",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "Hover me (bottom)",
      variant: "body1",
      tooltip: "Bottom tooltip with longer content to show how it wraps",
      tooltipSide: "bottom",
      className: "cursor-help underline decoration-dotted",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "3",
    xl: "3",
    type: "typography",
    element: {
      text: "Hover me (left)",
      variant: "body1",
      tooltip: "Left side tooltip",
      tooltipSide: "left",
      className: "cursor-help underline decoration-dotted",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "typography",
    element: {
      text: "Tooltip with custom delay",
      variant: "body1",
      tooltip: "This tooltip has a custom delay of 1500ms",
      tooltipDelay: 1500,
      className: "cursor-help underline decoration-dotted",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "typography",
    element: {
      text: "Tooltip on heading",
      variant: "h4",
      tooltip: "Even headings can have tooltips!",
      color: "blue",
      className: "cursor-help",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "4",
    xl: "4",
    type: "typography",
    element: {
      text: "Link with tooltip",
      variant: "body1",
      href: "https://example.com",
      target: "_blank",
      tooltip: "Click to visit external site",
      color: "blue",
      decoration: "underline",
    },
  },
];

export const containerCountryOverview: Container = {
  id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
  name: "CountryOverview",
  isArray: false,
  bins: countryOverviewBins,
  ...DEFAULT_CONTAINER_GRID,
  gap: "3",
};

export const containerCountryMetadata: Container = {
  id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
  name: "CountryMetadata",
  isArray: false,
  bins: countryMetadataBins,
  ...DEFAULT_CONTAINER_GRID,
  gap: "3",
};

export const containerCountryTypography: Container = {
  id: "c3d4e5f6-g7h8-9012-cdef-g23456789012",
  name: "CountryTypography",
  isArray: false,
  bins: countryTypographyBins,
  ...DEFAULT_CONTAINER_GRID,
  gap: "3",
};

/** Content rendered inside each Paper surface in the Paper demo tab. */
const paperCardContent: Bin[] = [
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "typography",
    justifySelf: "start",
    alignSelf: "start",
    element: {
      text: "Paper surface",
      variant: "subtitle1",
      weight: "bold",
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    justifySelf: "start",
    alignSelf: "start",
    element: {
      text: "Paper wraps a nested container and renders it on an elevated surface, mirroring MUI's Paper.",
    },
  },
];

const containerPaperCardContent: Container = {
  id: "p1a2b3c4-d5e6-7890-abcd-ef1234567890",
  name: "PaperCardContent",
  isArray: false,
  bins: paperCardContent,
  ...DEFAULT_CONTAINER_GRID,
  gap: "2",
};

/** Paper demo bins — shows the elevation scale and the outlined variant side by side. */
export const countryPaperBins: Bin[] = [
  {
    sm: "12",
    md: "4",
    lg: "4",
    xl: "4",
    type: "paper",
    justifySelf: "stretch",
    alignSelf: "start",
    element: {
      container: containerPaperCardContent,
      elevation: 1,
      variant: "elevation",
      style: { padding: "20px" },
    },
  },
  {
    sm: "12",
    md: "4",
    lg: "4",
    xl: "4",
    type: "paper",
    justifySelf: "stretch",
    alignSelf: "start",
    element: {
      container: containerPaperCardContent,
      elevation: 8,
      variant: "elevation",
      style: { padding: "20px" },
    },
  },
  {
    sm: "12",
    md: "4",
    lg: "4",
    xl: "4",
    type: "paper",
    justifySelf: "stretch",
    alignSelf: "start",
    element: {
      container: containerPaperCardContent,
      variant: "outlined",
      style: { padding: "20px" },
    },
  },
];

export const containerCountryPaper: Container = {
  id: "d4e5f6g7-h8i9-0123-defg-h34567890123",
  name: "CountryPaper",
  isArray: false,
  bins: countryPaperBins,
  ...DEFAULT_CONTAINER_GRID,
  gap: "3",
};

/**
 * Regex demo bins — each TextField uses the `regex` prop to restrict input.
 * Any keystroke that would make the value not match the pattern is rejected,
 * so the field can never hold an invalid character (an empty value is always
 * allowed so the field can be cleared).
 */
export const countryRegexBins: Bin[] = [
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "text",
    justifySelf: "start",
    alignSelf: "end",
    element: {
      text: "Regex-restricted inputs",
      isLabel: true,
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "textfield",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "lettersOnly",
      label: "Letters only",
      dataType: "text",
      isRequired: false,
      errorMessage: "",
      placeholder: "abcDEF",
      regex: "^[A-Za-z]*$",
      regexErrorMessage: "Only letters (A–Z) are allowed",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "textfield",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "digitsOnly",
      label: "Digits only",
      dataType: "text",
      isRequired: false,
      errorMessage: "",
      placeholder: "123456",
      regex: "^[0-9]*$",
      regexErrorMessage: "Only digits (0–9) are allowed",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "textfield",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "countryCode",
      label: "Country code (upper-case letters)",
      dataType: "text",
      isRequired: false,
      errorMessage: "",
      placeholder: "TH",
      regex: "^[A-Z]*$",
      regexErrorMessage: "Only upper-case letters (A–Z) are allowed",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "textfield",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "phone",
      label: "Phone (digits, +, -, space)",
      dataType: "tel",
      isRequired: false,
      errorMessage: "",
      placeholder: "+66 2-123-4567",
      regex: "^[0-9+\\-\\s]*$",
      regexErrorMessage: "Only digits, +, - and spaces are allowed",
    },
  },
  {
    sm: "12",
    md: "6",
    lg: "6",
    xl: "6",
    type: "textfield",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "email",
      label: "Email",
      dataType: "email",
      isRequired: false,
      errorMessage: "",
      placeholder: "name@example.com",
      regex: "^[A-Za-z0-9._%+\\-]*@?[A-Za-z0-9.\\-]*\\.?[A-Za-z]*$",
    },
  },
];

export const containerCountryRegex: Container = {
  id: "d4e5f6a7-b8c9-0123-def0-345678901234",
  name: "CountryRegex",
  isArray: false,
  bins: countryRegexBins,
  ...DEFAULT_CONTAINER_GRID,
  gap: "3",
};

/** The country tabs, extracted so they can be wrapped in a Paper surface. */
const countryTabsBins: Bin[] = [
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "tab",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      defaultValue: "overview",
      tabs: [
        {
          label: "Overview",
          value: "overview",
          container: containerCountryOverview,
        },
        {
          label: "Metadata",
          value: "metadata",
          container: containerCountryMetadata,
        },
        {
          label: "Typography",
          value: "typography",
          container: containerCountryTypography,
        },
        {
          label: "Regex",
          value: "regex",
          container: containerCountryRegex,
        },
        {
          label: "Paper",
          value: "paper",
          container: containerCountryPaper,
        },
      ],
    },
  },
];

export const containerCountryTabs: Container = {
  id: "e5f6g7h8-i9j0-1234-efgh-i45678901234",
  name: "CountryTabs",
  isArray: false,
  bins: countryTabsBins,
  ...DEFAULT_CONTAINER_GRID,
  gap: "3",
};

export const groupList: Bin[] = [
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "paper",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      container: containerCountryTabs,
      elevation: 2,
      variant: "elevation",
      style: { padding: "16px" },
    },
  },
  {
    type: "empty",
    sm: "11",
    md: "11",
    lg: "11",
    xl: "11",
    justifySelf: "stretch",
    alignSelf: "center",
  },
  {
    type: "modal",
    sm: "1",
    md: "1",
    lg: "1",
    xl: "1",
    align: "end",
    justifySelf: "end",
    alignSelf: "center",
    element: {
      id: "modalGroup",
      title: "Create Country",
      description: "modal",
      container: containerCountryDetail,
      maxWidth: "800px",
      minWidth: "700px",
      trigger: {
        label: "",
        actions: ["ClearCurrentFormSelected"],
        icon: "puls",
      },
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "datatable",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "dtCountry",
      title: "Countries",
      modalContainer: containerCountryDetail,
      modalMaxWidth: "800px",
      modalMinWidth: "700px",
      canEdit: true,
      canDelete: true,
      columns: [
        {
          accessor: "code",
          header: "Code",
          enableColumnFilter: true,
          enableSorting: true,
          align: "start",
        },
        {
          accessor: "name",
          header: "Name",
          enableColumnFilter: true,
          enableSorting: true,
          align: "start",
        },
        {
          accessor: "updated_at",
          header: "Update Date",
          enableColumnFilter: true,
          enableSorting: true,
          align: "start",
          useDateFormat: "DD/MM/YYYY HH:mm:ss",
        },
        {
          accessor: "updated_by_name",
          header: "Updated By",
          enableColumnFilter: true,
          enableSorting: true,
          align: "start",
        },
      ],
      apiDeleteInfo: {
        name: "deleteCountry",
        params: { id: "_id" },
        confirmBox: {
          title: "Delete Country",
          description: "Are you sure you want to delete this country?",
          True: ["StartLoading", "SubmitFormToDeleteAPI", "StopLoading"],
          False: [],
        },
        isReload: true,
        snackbarSuccess: { type: "success", message: "Country deleted successfully" },
        snackbarError: "$exception",
      },
      api: {
        name: "countries",
        paths: ["data"],
        body: {
          collectionId: { type: "value", key: "collectionId", value: "691e9963992636eb1560eadb" },
          offset: { type: "value", key: "offset", value: 0 },
          limit: { type: "value", key: "limit", value: 100 },
        },
      },
    },
  },
  {
    sm: "12",
    md: "12",
    lg: "12",
    xl: "12",
    type: "datatableeditable",
    justifySelf: "stretch",
    alignSelf: "stretch",
    element: {
      name: "dtCountryEditable",
      title: "Countries (Inline CRUD)",
      idKey: "_id",
      columns: [
        {
          accessorKey: "code",
          header: "Code",
          enableColumnFilter: true,
          enableSorting: true,
          align: "start",
          isRequired: true,
          validation: {
            requiredMessage: "Code is required",
            minLength: 2,
            maxLength: 5,
            pattern: "^[A-Za-z]+$",
            patternMessage: "Code must contain letters only",
          },
        },
        {
          accessorKey: "name",
          header: "Name",
          enableColumnFilter: true,
          enableSorting: true,
          align: "start",
          isRequired: true,
          validation: {
            requiredMessage: "Name is required",
            minLength: 2,
          },
        },
        {
          accessorKey: "updated_by_name",
          header: "Updated By",
          enableSorting: true,
          align: "start",
          editable: false,
        },
      ],
      apiCrud: {
        read: {
          name: "countries",
          paths: ["data"],
          query: {
            collectionId: "691e9963992636eb1560eadb",
            offset: 0,
            limit: 100,
          },
        },
        create: {
          name: "createCountry",
          snackbarSuccess: { type: "success", message: "Country created successfully" },
          snackbarError: "$exception",
        },
        update: {
          name: "updateCountry",
          params: { id: "_id" },
          snackbarSuccess: { type: "success", message: "Country updated successfully" },
          snackbarError: "$exception",
        },
        delete: {
          name: "deleteCountry",
          params: { id: "_id" },
          confirmBox: {
            title: "Delete Country",
            description: "Are you sure you want to delete this country?",
          },
          snackbarSuccess: { type: "success", message: "Country deleted successfully" },
          snackbarError: "$exception",
        },
      },
    },
  },
];

export const containerCountryList: Container[] = [
  {
    id: "7afc5dc0-d446-4ff4-ab17-8d81127e5ab2",
    name: "GroupList",
    isArray: false,
    bins: groupList,
    ...DEFAULT_CONTAINER_GRID,
    gap: "3",
    justifyItems: "stretch",
    alignItems: "start",
    justifyContent: "space-between",
    alignContent: "start",
  },
];
